---
title: "Joining Data"
author: "Daniel Truver"
date: "11/23/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(stringr)
load("house_mod.Rdata")
load("new_nyt_peeps.Rdata")
house_mod = house_mod %>%
  filter(Cand_Name != "cox, stephan")
filing = as.Date("2018-10-17")
```

```{r}
house_mod = house_mod %>%
  mutate(last_name = str_extract(Cand_Name, "^.+,")) %>%
  mutate(last_name = str_remove(last_name, ",")) %>%
  mutate(first_name = str_extract(Cand_Name, ",.+$")) %>%
  mutate(first_name = str_remove(first_name, ",\\s")) %>%
  mutate(full_name = paste(first_name, last_name))
dis_num = house_mod$Cand_Office_Dist
dis_num[!str_detect(dis_num, "\\d\\d")] = paste0("0",dis_num[!str_detect(dis_num, "\\d\\d")])
house_mod$Cand_Office_Dist = dis_num
house_mod$dist = paste(house_mod$Cand_Office_St, house_mod$Cand_Office_Dist, sep = "_")
```

```{r}
# for(st in state.abb){
joins = lapply(state.abb[-2], function(st){
  # st = "AL"
  t = new_nyt_peeps[[st]]
  state = filter(house_mod, Cand_Office_St == st)
  t.lasts = str_remove(t$dems, "[^a-z]") %>%
    str_replace(.,"snchez ", "sanchez") %>%
    str_replace(.," jr", "")
  lasts = str_remove(state$last_name, "-")
  in.join_lasts = unlist(lapply(lasts, function(l){
    temp = which(t.lasts == l)
    ifelse(length(temp) < 1, NA, temp)
  }))
  state_gen = state[!is.na(in.join_lasts),]
  state_gen = state_gen %>% 
    filter(Coverage_End_Date == filing) %>%
    filter(Cand_Party_Affiliation == "DEM")
  state_gen = state_gen %>% 
    select(Cand_Office_St, dist, Cand_Incumbent_Challenger_Open_Seat,
           Total_Disbursement)
  new_t = inner_join(state_gen, t, by = "dist")
  new_t
})
# }
names(joins) = state.abb[-2]
```

```{r to_be_removed}
##### REMOVE THIS EVENTUALLY AFTER FEC UPDATE
ex_state = which(names(joins) == "DE")
new_joins = joins[-ex_state]
exclude_st = c("AK", "DE")
##### REMOVE THIS EVENTUALLY AFTER FEC UPDATE
```

```{r}
load("new_nyt_calls.Rdata")
load("new_nyt_calls2016.Rdata")
money_2018 = NULL
for(i in seq_along(new_joins)){
  money_2018 = rbind(money_2018, new_joins[[i]])
}
calls_2018 = new_nyt_calls %>% select(Dem., dist)
names(calls_2018) = c("prop_dem2018", "dist")
calls_2016 = new_nyt_calls2016 %>% select(Dem., dist)
names(calls_2016) = c("prop_dem2016", "dist")
t = inner_join(money_2018, calls_2018, by = "dist")
money_calls2018 = inner_join(t, calls_2016, by = "dist")
```

```{r}
load("census_districts.Rdata")
wide_census = lapply(state.abb ,function(st){
  # st = "AL"
  t = new_states[[st]]
  vars = paste(t$subject, t$title, sep = "_")
  vars = str_replace_all(vars, "\\s", "_")
  dist = names(t)[-(1:2)]
  dist = str_replace_all(dist, ".At.Large.", "00")
  new_t = t %>% select(-subject, -title) %>% t() %>% as.data.frame()
  new_t$dist = dist
  names(new_t) = c(vars, "dist")
  new_t
})
census_2018 = NULL
for(i in seq_along(wide_census)){
  census_2018 = rbind(census_2018, wide_census[[i]])
}
full_data = inner_join(money_calls2018, census_2018, by = "dist") 
save(full_data, "full_data.Rdata")
# lm_form = as.formula("log(Total_Disbursement)~.-Cand_Office_St-dist-prop_dem2018-dems")
```

```{r}
# this chunk runs everything else
```


<!--
```{r}
st = "CA"
# name_join = lapply(state.abb, function(st){
  t = new_peeps[[st]]
  join_peeps = tolower(t$dems)
  join_peeps = str_extract(join_peeps, "[a-z]+\\s[a-z]+\\s")
  house_state = house_mod %>%
    filter(Cand_Office_St == st)
  lasts = str_remove(house_state$last_name, "-")
  first = house_state$first_name
  fulls = house_state$full_name
  in.join_lasts = unlist(lapply(lasts, function(l){
    temp = which(str_detect(join_peeps, l))
    ifelse(length(temp) < 1, NA, temp)
  }))
  house_state = house_state[!is.na(in.join_lasts),]
  t$unit_district = rownames(t)
  house_state = house_state %>%
    mutate(unit_district = paste(Cand_Office_St, Cand_Office_Dist, sep = "_"))
  new_t = inner_join(t, house_state, by = "unit_district") 
  new_t = new_t %>%
    select(full_name, uncon, unit_district, Cand_Party_Affiliation,
           Cand_Incumbent_Challenger_Open_Seat, Total_Disbursement, Coverage_End_Date) %>%
    filter(Cand_Party_Affiliation == "DEM")
# })
# names(name_join) = state.abb
```
--->